[project]
name = "ace-step-wrangler"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.133.1",
    "httpx>=0.28.1",
    "uvicorn>=0.41.0",
]
